name = "nuclear"
main = "build/worker/shim.mjs"
compatibility_date = "2025-08-15"
minify = true

[[kv_namespaces]]
binding = "SIREN"
id = "2e9fa46e3a984694a31c75f10057f8b4"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "2bcfbfba-b446-4ad5-93ad-72af9e008f61"
MAIN_PAGE_URL = "https://siren.cloudaccess.host/"
PROXY_KV_URL = "https://siren.cloudaccess.host/best-latency.json"
